### ISSUE TITLE
Can't get package through pip

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [lanshark/django-encrypted-model-fields#6]
Hello dear friend,

I would like to inform you that the package name "django-encrypted-fields" in pip is already used by the following library: https://github.com/defrex/django-encrypted-fields

Maybe you could (once again) change the package name ?

Regards,

Jonathan DEKHTIAR

**Comment by Wegi** [comment]
Is this current? I had no problems retrieving the package.

**Comment by lanshark** [comment]
The name of this package is django-encrypted-model-fields.
